### PR TITLE
Feature/accounts card order

### PR DESCRIPTION
**Pull request by devights**
rebasing on qa wasn't straightforward so this is just going to develop

### CODE REVIEW

**Comment by klpittman** [comment]
@fanglinfang I'm not sure I'm the best person to review this. @hlee2 would be a better judge if the cards are all in the correct order as she's most familiar with the spec.

**Comment by hlee2** [comment]
- As the viewport size increase or decrease, cards gets stacked to a single column around 1280w.
- Stacked cards(1 column) stay even after the viewport size increase to 1280+. Expected to shift to 2 columns.

**Comment by hlee2** [comment]
In 2 column display, the library card and the U-pass card are switched for javerage, jbothell, jnew. But the right order for jinter and jeos. 
Expected card order is 1)Tuition 2)Husky 3) Library 4)Upass 5) NetID from left to right.

**Comment by devights** [comment]
@hlee2 I can't repro your issue with the card order, it's showing in the defined order top>bottom, left>right.

otherwise other issues have been addressed.

**Comment by vegitron** [comment]
The goal of adding the remove_card method was reducing the amount of code, so that it would be easier for card authors and more reliable.  A remove_card method per card just adds more code around what was there before.  I was thinking of something like this, potentially in myuw_m.js:

function remove_card(target) {
    $(target).remove();
    $(window).trigger("card-hide");
}

**Comment by devights** [comment]
@vegitron Got it, I mis-understood what you were asking first and figured there was some benefit to allowing each card to add extra functionality to it's remove_card method (unsure what that would be at this point).  made the method global!

**Comment by hlee2** [comment]
Verified 1) changing between single column and 2 columns as the viewport increase/decrease 2) Card order.

**Pull request merged**
