### PR TITLE
Hotfix/muwm 3934

### PR DESCRIPTION
**Pull request by fanglinfang**
https://jira.cac.washington.edu/browse/MUWM-3934

On my-test

### CODE REVIEW

**Comment by klpittman** [comment]
Looks like everything is working. Is it possible to change this "Cancel" button to "Close" here though? "Cancel" doesn't really make sense after the request has been already submitted.

screen_shot_2017-09-01_at_10_39_05_am

**Comment by klpittman** [comment]
Looks like some handlebar comments are being printed on the Advanced create form for classes with secondary sections.

Found with netid "kaoru" on my-test

myuw__teaching_section_and_pepper_-_stone_love

**Comment by fanglinfang** [comment]
prefer use html comment instead of handlebar comment

**Comment by klpittman** [comment]
similarly, it looks like the comments are also shown on the Create Mailing List popup for primary sections w/ secondary sections attached.

netid: kaoru, my-test.
Japan 111 B Autumn 2017

myuw__teaching_section

**Comment by fanglinfang** [comment]
should be fixed by now

**Pull request merged**
