### PR TITLE
Bugfix/acal page fixes

### PR DESCRIPTION
**Pull request by devights**
resolves MUWM-3842  and MUWM-3843

### CODE REVIEW

**Comment by vegitron** [comment]
For the MUWM-3842 fix, the root cause was events that don't have a year attached.  This fix prevents the duplicate headers, but if you take the year off independence day 2013 in mock data, it's out of order, and there's a blank header row.
screen shot 2017-06-26 at 9 41 14 am

**Comment by vegitron** [comment]
What's the goal with the fix for MUWM-3843?  That production data has independence day in spring quarter.  Grouping it there doesn't seem like it's the right thing to do.

**Comment by devights** [comment]
I'm waiting on William's opinion on the 3843 issue since he had an issue with the current handling, for the issue with blank headers there's this bug MUWM-3841 that's waiting on ux.

**Comment by devights** [comment]
Closing due to conversation with William, plan will be to fix ical data in trumba, consider logging events without term data in future to identify early and fix (or find a better data provider)

**Pull request closed without merging**
