### PR TITLE
Feature/teaching summary

### PR DESCRIPTION
**Pull request by fanglinfang**
https://trello.com/c/3JpMY3Bp
https://jira.cac.washington.edu/browse/MUWM-3941

I have checked the code changes.

### CODE REVIEW

**Comment by bexar** [comment]
Missing course colors on summary and visual schedule (and teaching page as well)
screen shot 2017-09-25 at 12 48 44 pm

**Comment by bexar** [comment]
On mobile view (iphone 5, others), summary schedule content extends past right hand margin of card 
screen shot 2017-09-25 at 12 52 48 pm

**Comment by fanglinfang** [comment]
@bexar  I have color block on mine.  Try a hard refresh

**Comment by klpittman** [comment]
I don't get color blocks for 2013-04-15 00:00:01, but I do get them on 2013-09-15 00:00:01 date override.

**Comment by klpittman** [comment]
@bexar good catch. Since we are prioritizing desktop for instructors, I say we push forward with the release still. I will need to refactor some of that markup to get that to work properly for mobile.

**Comment by fanglinfang** [comment]
i always have color on 2013-04-15

**Comment by bexar** [comment]
@klpittman sounds good on the mobile comment.

**Comment by klpittman** [comment]
@fanglinfang with some minor modifications I can get it to be like this. Still not great. Do you think this is better than nothing?
myuw__home

**Comment by fanglinfang** [comment]
@klpittman that see,s to be the same as what i see on my phone now

**Comment by klpittman** [comment]
the code had nonwrapping spaces between the enrollment counts before. Now that line is allowed to break on my build.

**Pull request merged**
