### PR TITLE
Hotfix/muwm 3794

### PR DESCRIPTION
**Pull request by hlee2**
500 error page update: Email service link and the ESS to Workday

### CODE REVIEW

**Comment by hlee2** [comment]
@wmwash Updated the outage template and removed email hyperlink on the 500 template.

**Comment by wmwash** [comment]
@hlee2 I'm not seeing the email links on the outage card...

**Comment by hlee2** [comment]
oops. fixed.

**Comment by hlee2** [comment]
@wmwash How can I view the rendered outage template? Did you say updating the template is enough? I need some help triggering the SWS outage to render it.

**Comment by wmwash** [comment]
@hlee2 To have confidence that the fix was made and nothing else was inadvertently changed, we should render this in the browser. And for that, talk to Stephen about how to render it. When you find out, please document in the error spec that you created what was required to render the template. Thanks!

**Pull request closed without merging**
